/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return application status and version.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bootstrap
         * @description Return the app's bootstrap state for the frontend to decide routing.
         */
        get: operations["bootstrap_api_v1_auth_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user.  Only allowed when no users exist (first-boot).
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verify credentials and issue a pre-auth cookie.
         *
         *     Returns ``{"next": "mfa_setup"}`` if the user has not yet bound TOTP,
         *     or ``{"next": "mfa_verify"}`` if TOTP is already configured.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mfa Setup
         * @description Generate a pending TOTP secret for the authenticated user.
         *
         *     Requires the ``jai_pre_auth`` cookie (set by the login endpoint).
         *     The secret is **not** persisted until the user successfully verifies a
         *     code via ``POST /auth/mfa/verify``.
         */
        post: operations["mfa_setup_api_v1_auth_mfa_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mfa Verify
         * @description Verify a TOTP code and upgrade the pre-auth cookie to a full session.
         *
         *     Two cases:
         *
         *     1. **First binding** (user has no ``totp_secret``): the code is verified
         *        against the pending secret generated by ``/mfa/setup``.  On success,
         *        ``totp_secret`` is persisted and ``mfa_enabled`` is set to ``True``.
         *     2. **Subsequent login** (user has ``mfa_enabled=True``): the code is
         *        verified against the stored ``totp_secret``.
         *
         *     On success the ``jai_pre_auth`` cookie is cleared and a ``jai_session``
         *     cookie is set.
         */
        post: operations["mfa_verify_api_v1_auth_mfa_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the session cookie and pre-auth cookie.
         *
         *     Public and idempotent: it always returns cookie-clearing response headers,
         *     even when the incoming cookies are missing, expired, or no longer
         *     verifiable (e.g. after a secret rotation).  Since the cookies are
         *     ``httpOnly`` the frontend cannot clear them on its own, so the server must
         *     do so unconditionally.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Request a password reset.
         *
         *     **Always returns 202** to prevent email-enumeration.  When the user exists
         *     and SMTP is configured, a reset-token email is sent in the background.
         */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Reset a user's password using a valid reset token.
         *
         *     Returns 204 on success, 400 on invalid/expired token or password validation
         *     failure.
         */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the currently authenticated user (requires MFA completed).
         */
        get: operations["me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Company
         * @description Return the company profile.
         *
         *     Returns ``204 No Content`` if the company has not been created yet.
         */
        get: operations["read_company_api_v1_company_get"];
        /**
         * Write Company
         * @description Create or update the singleton company profile.
         *
         *     On first creation, also:
         *       - Set ``onboarding.completed = true``.
         *       - Link the owner's ``company_id`` to the new company.
         */
        put: operations["write_company_api_v1_company_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/company/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Logo
         * @description Serve the company logo binary with caching headers.
         */
        get: operations["serve_logo_api_v1_company_logo_get"];
        /**
         * Upload Logo
         * @description Upload or replace the company logo.
         *
         *     Accepts PNG, JPEG, WebP, or SVG.  SVG content is sanitized (red-line 7).
         *     Maximum size: 512 KB.
         */
        put: operations["upload_logo_api_v1_company_logo_put"];
        post?: never;
        /**
         * Delete Logo
         * @description Remove the company logo.
         */
        delete: operations["delete_logo_api_v1_company_logo_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/smtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Smtp Settings
         * @description Return the current SMTP settings (password desensitised).
         */
        get: operations["get_smtp_settings_api_v1_settings_smtp_get"];
        /**
         * Update Smtp Settings
         * @description Update SMTP settings. If ``password`` is ``None``, the existing password is kept.
         */
        put: operations["update_smtp_settings_api_v1_settings_smtp_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/smtp/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Smtp Settings
         * @description Send a test email to the owner's address using current SMTP config.
         *
         *     Returns ``{"status": "sent"}`` on success or raises 400 with error detail.
         */
        post: operations["test_smtp_settings_api_v1_settings_smtp_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/numbering": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Numbering Config
         * @description Return the invoice numbering configuration for the current company.
         *
         *     Returns the COMPANY-level setting, or the default if not yet configured.
         *     The actual numbering engine is implemented in M5; M2 only persists the
         *     configuration.
         */
        get: operations["get_numbering_config_api_v1_settings_numbering_get"];
        /**
         * Update Numbering Config
         * @description Update the invoice numbering configuration for the current company.
         *
         *     Stored at COMPANY level (scope = company.id).  Requires owner role.
         */
        put: operations["update_numbering_config_api_v1_settings_numbering_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Preferences
         * @description Return the current user's effective preferences.
         *
         *     Resolves via ``USER(user.id) → COMPANY(user.company_id) → GLOBAL``.
         *     Returns defaults when no setting exists at any level.
         */
        get: operations["get_user_preferences_api_v1_settings_me_get"];
        /**
         * Update User Preferences
         * @description Update the current user's preferences (USER level, scope = user.id).
         */
        put: operations["update_user_preferences_api_v1_settings_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_logo_api_v1_company_logo_put */
        Body_upload_logo_api_v1_company_logo_put: {
            /** File */
            file: string;
        };
        /**
         * BootstrapResponse
         * @description Returned by ``GET /auth/bootstrap`` – drives frontend routing.
         */
        BootstrapResponse: {
            /** Registration Open */
            registration_open: boolean;
            /** Onboarding Completed */
            onboarding_completed: boolean;
        };
        /**
         * CompanyLogoRead
         * @description Response body for ``PUT /api/v1/company/logo``.
         */
        CompanyLogoRead: {
            /** Logo Url */
            logo_url: string;
            /** Mime Type */
            mime_type: string;
            /** Byte Size */
            byte_size: number;
        };
        /**
         * CompanyRead
         * @description Response body for ``GET /api/v1/company`` and ``PUT``.
         */
        CompanyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Vat Id */
            vat_id?: string | null;
            /** Coc Number */
            coc_number?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
            /** Address Line1 */
            address_line1?: string | null;
            /** Address Line2 */
            address_line2?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** City */
            city?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Base Currency */
            base_currency: string;
            /**
             * Has Logo
             * @default false
             */
            has_logo?: boolean;
            /** Logo Url */
            logo_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CompanyWrite
         * @description Request body for ``PUT /api/v1/company``.
         */
        CompanyWrite: {
            /** Name */
            name: string;
            /** Vat Id */
            vat_id?: string | null;
            /** Coc Number */
            coc_number?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Website */
            website?: string | null;
            /** Address Line1 */
            address_line1?: string | null;
            /** Address Line2 */
            address_line2?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** City */
            city?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Base Currency */
            base_currency: string;
        };
        /**
         * ForgotPasswordRequest
         * @description Body for ``POST /auth/forgot-password``.
         */
        ForgotPasswordRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response body for the health-check endpoint.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * InvoiceNumberingConfig
         * @description Invoice numbering template and sequence configuration.
         *
         *     Stored at ``COMPANY`` level with key ``SETTING_KEY_INVOICE_NUMBERING``
         *     (``"invoice.numbering"``).  M2 only persists the configuration; the
         *     rendering / sequence / concurrency-safe engine is implemented in M5.
         *
         *     Fields are intentionally minimal — M5 will extend when the engine is built.
         */
        InvoiceNumberingConfig: {
            /**
             * Template
             * @description Numbering template with placeholders.  M5 implements rendering.
             * @default {{SERIES:INV}}-{{SEQUENCE:6}}
             */
            template?: string;
            /**
             * Sequence Start
             * @description Starting number for the sequence counter.  M5 uses this.
             * @default 1
             */
            sequence_start?: number;
        };
        /**
         * LoginRequest
         * @description Body for ``POST /auth/login``.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Returned by ``POST /auth/login``.
         *
         *     ``next`` indicates the required next step:
         *     - ``"mfa_setup"``: user has not yet bound TOTP → show setup wizard.
         *     - ``"mfa_verify"``: user already has TOTP → prompt for verification code.
         */
        LoginResponse: {
            /**
             * Next
             * @enum {string}
             */
            next: "mfa_setup" | "mfa_verify";
        };
        /**
         * MfaSetupResponse
         * @description Returned by ``POST /auth/mfa/setup``.
         */
        MfaSetupResponse: {
            /** Secret */
            secret: string;
            /** Otpauth Uri */
            otpauth_uri: string;
        };
        /**
         * MfaVerifyRequest
         * @description Body for ``POST /auth/mfa/verify``.
         */
        MfaVerifyRequest: {
            /** Code */
            code: string;
        };
        /**
         * RegisterRequest
         * @description Body for ``POST /auth/register`` – only the fields a client may set.
         *
         *     Defined locally (rather than reusing fastapi-users' ``BaseUserCreate``) so
         *     the public contract is exactly ``{email, password}`` and never exposes
         *     ``is_active`` / ``is_superuser`` / ``is_verified``.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ResetPasswordRequest
         * @description Body for ``POST /auth/reset-password``.
         */
        ResetPasswordRequest: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /**
         * SmtpSettingsRead
         * @description SMTP settings as returned by the API – password is desensitised.
         */
        SmtpSettingsRead: {
            /**
             * Host
             * @default
             */
            host?: string;
            /**
             * Port
             * @default 587
             */
            port?: number;
            /**
             * Username
             * @default
             */
            username?: string;
            /**
             * Password Set
             * @default false
             */
            password_set?: boolean;
            /**
             * From Email
             * @default
             */
            from_email?: string;
            /**
             * From Name
             * @default
             */
            from_name?: string;
            /**
             * Use Tls
             * @default true
             */
            use_tls?: boolean;
            /**
             * Use Ssl
             * @default false
             */
            use_ssl?: boolean;
        };
        /**
         * SmtpSettingsUpdate
         * @description Body for ``PUT /settings/smtp``.
         */
        SmtpSettingsUpdate: {
            /** Host */
            host: string;
            /**
             * Port
             * @default 587
             */
            port?: number;
            /**
             * Username
             * @default
             */
            username?: string;
            /** Password */
            password?: string | null;
            /**
             * From Email
             * Format: email
             */
            from_email: string;
            /**
             * From Name
             * @default
             */
            from_name?: string;
            /**
             * Use Tls
             * @default true
             */
            use_tls?: boolean;
            /**
             * Use Ssl
             * @default false
             */
            use_ssl?: boolean;
        };
        /**
         * UserPreferences
         * @description Per-user preferences stored at USER level.
         *
         *     Stored at ``USER`` level with key ``SETTING_KEY_USER_PREFERENCES``
         *     (``"user.preferences"``).  The first real USER-level preference is the
         *     theme selection (dark mode).  More preferences will be added in later
         *     milestones.
         */
        UserPreferences: {
            /**
             * Theme
             * @description UI theme preference: 'system' follows OS, 'light' or 'dark' overrides.
             * @default system
             * @enum {string}
             */
            theme?: "system" | "light" | "dark";
        };
        /**
         * UserRead
         * @description User response schema – returned by ``GET /users/me`` and auth endpoints.
         */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active?: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser?: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified?: boolean;
            /**
             * Role
             * @default owner
             */
            role?: string;
            /**
             * Mfa Enabled
             * @default false
             */
            mfa_enabled?: boolean;
            /** Company Id */
            company_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    bootstrap_api_v1_auth_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mfa_setup_api_v1_auth_mfa_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaSetupResponse"];
                };
            };
        };
    };
    mfa_verify_api_v1_auth_mfa_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    read_company_api_v1_company_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description No company profile yet */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    write_company_api_v1_company_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_logo_api_v1_company_logo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                    "image/webp": string;
                    "image/svg+xml": string;
                };
            };
            /** @description No logo uploaded */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_logo_api_v1_company_logo_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_logo_api_v1_company_logo_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyLogoRead"];
                };
            };
            /** @description Invalid file type, too large, or no company */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_logo_api_v1_company_logo_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No logo to delete */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_smtp_settings_api_v1_settings_smtp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmtpSettingsRead"];
                };
            };
        };
    };
    update_smtp_settings_api_v1_settings_smtp_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmtpSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmtpSettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_smtp_settings_api_v1_settings_smtp_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_numbering_config_api_v1_settings_numbering_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceNumberingConfig"];
                };
            };
        };
    };
    update_numbering_config_api_v1_settings_numbering_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceNumberingConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceNumberingConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_preferences_api_v1_settings_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
        };
    };
    update_user_preferences_api_v1_settings_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
