/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressFieldsForm: typeof import('./components/AddressFieldsForm.vue')['default']
    AiSettingsForm: typeof import('./components/settings/AiSettingsForm.vue')['default']
    AppLayout: typeof import('./components/AppLayout.vue')['default']
    DictionarySettings: typeof import('./components/settings/DictionarySettings.vue')['default']
    DocumentDefaultsSettings: typeof import('./components/settings/DocumentDefaultsSettings.vue')['default']
    DocumentSendDialog: typeof import('./components/DocumentSendDialog.vue')['default']
    EmailLogPanel: typeof import('./components/EmailLogPanel.vue')['default']
    EmailTemplatesSettings: typeof import('./components/settings/EmailTemplatesSettings.vue')['default']
    InvoicePaymentPanel: typeof import('./components/InvoicePaymentPanel.vue')['default']
    MileageSettings: typeof import('./components/settings/MileageSettings.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NH4: typeof import('naive-ui')['NH4']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NResult: typeof import('naive-ui')['NResult']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    PdfPreviewDialog: typeof import('./components/PdfPreviewDialog.vue')['default']
    PreferenceSettings: typeof import('./components/settings/PreferenceSettings.vue')['default']
    QuotePaymentPanel: typeof import('./components/QuotePaymentPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./components/settings/SettingsPanel.vue')['default']
    SmtpSettingsForm: typeof import('./components/settings/SmtpSettingsForm.vue')['default']
    ThemeSettings: typeof import('./components/settings/ThemeSettings.vue')['default']
  }
}
